/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        System.out.println("Chọn chức năng: ");
        System.out.println("1. Sign In");
        System.out.println("2. Exit");
        if(scanner.nextInt() == 1){
            SignIn(scanner);
        } else {
            System.out.println("Kết thúc");
        }
    }

    private static void SignIn(Scanner scanner){
        User user = new User();
        System.out.print("Nhập user (user đúng: LinhPham): ");
        user.setUsername(scanner.next());
        System.out.print("Nhập Password (Password đúng: 0366286668): ");
        user.setPassword(scanner.next());

        System.out.println(user.SignIn());
    }
}

class User{
    private String username, password;

    private String UserNameBase = "LinhPham";
    private String PasswordBase = "0366286668";

    public User() {
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String SignIn(){
        if(this.username.equals(this.UserNameBase) && this.password.equals(this.PasswordBase)) return "Login Success";

        if(!this.username.equals(this.UserNameBase)) return "Sai UserName";

        return "Sai Password";

    }
}
